import { createHmac } from "node:crypto"
import type {
  ChatPermissionPolicy,
  ToolRequest,
  ToolRequestDecision,
  ToolRequestStatus,
} from "../shared/permission-policy"
import { POLICY_TERMINAL_STATUSES } from "../shared/permission-policy"
import { policy } from "./permission-gate"
import { canonicalArgsHash } from "./canonical-args"
import type { EventStore } from "./event-store"

export interface ToolCallbackServiceArgs {
  store: EventStore
  serverSecret: string
  now: () => number
  /**
   * Fires after any persisted state change (submit creates pending, answer /
   * cancel / cancelAllForChat resolves pending). The server wires this to
   * router.scheduleChatStateBroadcast so the UI sees a new pending_tool_request
   * the moment the model emits the tool call, instead of waiting for the next
   * unrelated broadcast to flush the read model.
   */
  onStateChange?: (chatId: string) => void
}

export interface ToolCallbackSubmitArgs {
  chatId: string
  sessionId: string
  toolUseId: string
  toolName: string
  args: Record<string, unknown>
  chatPolicy: ChatPermissionPolicy
  cwd: string
}

export interface ToolCallbackResult {
  status: ToolRequestStatus
  decision: ToolRequestDecision
  mismatchReason?: string
}

export interface ToolCallbackService {
  submit(args: ToolCallbackSubmitArgs): Promise<ToolCallbackResult>
  answer(id: string, decision: ToolRequestDecision): Promise<void>
  cancel(id: string, reason: string): Promise<void>
  cancelAllForChat(chatId: string, reason: string): Promise<void>
  recoverOnStartup(): Promise<void>
}

// Sentinel: the durable approval protocol no longer enforces a wall-clock
// timeout on ask-style pending records. Match upstream Claude Code (CLI),
// which blocks the turn until the user answers or explicitly cancels. The
// field stays in the persisted shape for read-model compatibility.
const NEVER_EXPIRES = Number.MAX_SAFE_INTEGER

export function createToolCallbackService(opts: ToolCallbackServiceArgs): ToolCallbackService {
  interface PendingWaiter {
    resolve: (r: ToolCallbackResult) => void
  }
  const waiters = new Map<string, PendingWaiter[]>()
  // Tracks the canonical (toolName, canonicalArgsHash) per (chatId, sessionId,
  // toolUseId) so we detect mismatched retries. toolUseId is generated by the
  // claude CLI per-session and restarts at "1" for each new spawn, so keying
  // by toolUseId alone collides across chats / restarts.
  const seenToolUseIds = new Map<string, { id: string; toolName: string; canonicalArgsHash: string }>()
  function seenKey(s: { chatId: string; sessionId: string; toolUseId: string }): string {
    return `${s.chatId}|${s.sessionId}|${s.toolUseId}`
  }
  // In-memory mirror of persisted records keyed by id — lets submit() check
  // existing state synchronously (before the first await) so that concurrent
  // calls within the same event-loop turn see the correct state.
  const inMemory = new Map<string, ToolRequest>()

  function hmacId(s: ToolCallbackSubmitArgs, hash: string): string {
    const h = createHmac("sha256", opts.serverSecret)
    h.update(`${s.chatId}|${s.sessionId}|${s.toolUseId}|${s.toolName}|${hash}`)
    return h.digest("hex")
  }

  function resolveWaiters(id: string, result: ToolCallbackResult) {
    const ws = waiters.get(id) ?? []
    waiters.delete(id)
    for (const w of ws) w.resolve(result)
  }

  function notify(chatId: string) {
    if (!opts.onStateChange) return
    try {
      opts.onStateChange(chatId)
    } catch (err) {
      console.warn("[tool-callback] onStateChange threw", err)
    }
  }

  async function persistPut(req: ToolRequest): Promise<void> {
    inMemory.set(req.id, { ...req })
    await opts.store.putToolRequest(req)
    notify(req.chatId)
  }

  async function persistResolve(
    id: string,
    update: { status: ToolRequestStatus; decision: ToolRequestDecision; resolvedAt: number; mismatchReason?: string },
  ): Promise<void> {
    const existing = inMemory.get(id)
    if (existing) {
      inMemory.set(id, { ...existing, ...update })
    }
    await opts.store.resolveToolRequest(id, update)
    if (existing) notify(existing.chatId)
  }

  const svc: ToolCallbackService = {
    submit(args) {
      const hash = canonicalArgsHash(args.args)
      const id = hmacId(args, hash)

      // ── Arg-mismatch check (synchronous, no I/O) ──────────────────────────
      const seen = seenToolUseIds.get(seenKey(args))
      if (seen && (seen.toolName !== args.toolName || seen.canonicalArgsHash !== hash)) {
        const reason = `argument_mismatch: canonicalArgsHash differs from prior submission for toolUseId=${args.toolUseId}`
        const decision: ToolRequestDecision = { kind: "deny", reason }
        const now = opts.now()
        const mismatchReq: ToolRequest = {
          id,
          chatId: args.chatId,
          sessionId: args.sessionId,
          toolUseId: args.toolUseId,
          toolName: args.toolName,
          arguments: args.args,
          canonicalArgsHash: hash,
          policyVerdict: "auto-deny",
          status: "arg_mismatch",
          decision,
          mismatchReason: reason,
          createdAt: now,
          resolvedAt: now,
          expiresAt: now,
        }
        // Await persistence so a caller scanning the store after submit() sees the record.
        return persistPut(mismatchReq).then(() => ({ status: "arg_mismatch" as const, decision, mismatchReason: reason }))
      }

      // ── Idempotency: check in-memory mirror (synchronous) ─────────────────
      const existing = inMemory.get(id)
      if (existing && POLICY_TERMINAL_STATUSES.has(existing.status)) {
        return Promise.resolve({
          status: existing.status,
          decision: existing.decision ?? { kind: "deny", reason: "unknown" },
          mismatchReason: existing.mismatchReason,
        })
      }
      if (existing) {
        // Already pending — attach a new waiter.
        return new Promise<ToolCallbackResult>((resolve) => {
          const list = waiters.get(id) ?? []
          list.push({ resolve })
          waiters.set(id, list)
        })
      }

      // ── New request ───────────────────────────────────────────────────────
      const verdict = policy.evaluate({
        toolName: args.toolName,
        args: args.args,
        chatPolicy: args.chatPolicy,
        cwd: args.cwd,
      })
      const now = opts.now()
      const req: ToolRequest = {
        id,
        chatId: args.chatId,
        sessionId: args.sessionId,
        toolUseId: args.toolUseId,
        toolName: args.toolName,
        arguments: args.args,
        canonicalArgsHash: hash,
        policyVerdict: verdict.verdict,
        status: "pending",
        createdAt: now,
        expiresAt: NEVER_EXPIRES,
      }

      // Register synchronously so subsequent calls within the same tick see it.
      inMemory.set(id, { ...req })
      seenToolUseIds.set(seenKey(args), { id, toolName: args.toolName, canonicalArgsHash: hash })

      if (verdict.verdict === "auto-allow" || verdict.verdict === "auto-deny") {
        const decision: ToolRequestDecision = verdict.verdict === "auto-allow"
          ? { kind: "allow", reason: verdict.reason }
          : { kind: "deny", reason: verdict.reason }
        const resolvedReq: ToolRequest = { ...req, status: "answered", decision, resolvedAt: now }
        inMemory.set(id, resolvedReq)
        // Persist in background; caller gets immediate result. No broadcast —
        // auto-resolved tool calls never show as a pending prompt to the user.
        void (async () => {
          await opts.store.putToolRequest(req)
          await opts.store.resolveToolRequest(id, { status: "answered", decision, resolvedAt: now })
        })()
        return Promise.resolve({ status: "answered", decision })
      }

      // "ask" verdict → persist then wait for external answer. Broadcast
      // synchronously after the JSONL append so the UI gets the
      // pending_tool_request snapshot the moment the model emits the call.
      const pendingPromise = new Promise<ToolCallbackResult>((resolve) => {
        const list = waiters.get(id) ?? []
        list.push({ resolve })
        waiters.set(id, list)
      })
      void persistPut(req)
      return pendingPromise
    },

    async answer(id, decision) {
      const existing = inMemory.get(id) ?? opts.store.getToolRequest(id)
      if (!existing || POLICY_TERMINAL_STATUSES.has(existing.status)) return
      await persistResolve(id, { status: "answered", decision, resolvedAt: opts.now() })
      resolveWaiters(id, { status: "answered", decision })
    },

    async cancel(id, reason) {
      const existing = inMemory.get(id) ?? opts.store.getToolRequest(id)
      if (!existing || POLICY_TERMINAL_STATUSES.has(existing.status)) return
      const decision: ToolRequestDecision = { kind: "deny", reason: `canceled: ${reason}` }
      await persistResolve(id, { status: "canceled", decision, resolvedAt: opts.now() })
      resolveWaiters(id, { status: "canceled", decision })
    },

    async cancelAllForChat(chatId, reason) {
      // Collect pending ids from in-memory mirror first (synchronous), then
      // also check store for any records loaded before this service started.
      const pendingIds = new Set<string>()
      for (const [id, req] of inMemory.entries()) {
        if (req.chatId === chatId && req.status === "pending") pendingIds.add(id)
      }
      const storeList = opts.store.listPendingToolRequests(chatId)
      for (const req of storeList) pendingIds.add(req.id)
      for (const id of pendingIds) await svc.cancel(id, reason)
    },

    async recoverOnStartup() {
      const all = opts.store.scanAllToolRequests()
      for (const req of all) {
        if (req.status !== "pending") continue
        const decision: ToolRequestDecision = { kind: "deny", reason: "server_restarted" }
        await persistResolve(req.id, { status: "session_closed", decision, resolvedAt: opts.now() })
      }
    },
  }

  return svc
}

/**
 * Creates a ToolCallbackService and immediately calls recoverOnStartup()
 * to fail-close any pending tool requests left over from a previous server
 * run.  KANNA_SERVER_SECRET should be set in the environment for stable
 * HMAC ids within a process lifetime; if unset, a fresh random UUID is used
 * (cross-restart idempotency is not required because recoverOnStartup()
 * already closes all pending records).
 */
export async function initToolCallbackOnBoot(args: {
  store: EventStore
  serverSecret: string
  now?: () => number
  onStateChange?: (chatId: string) => void
}): Promise<ToolCallbackService> {
  const svc = createToolCallbackService({
    store: args.store,
    serverSecret: args.serverSecret,
    now: args.now ?? (() => Date.now()),
    onStateChange: args.onStateChange,
  })
  await svc.recoverOnStartup()
  return svc
}
