// Auto-generated by wiki/scripts/extract-env-vars.ts. Do not edit by hand.
export interface EnvVar { name: string; default: string; description: string }
export const envVars: EnvVar[] = [
  { name: 'KANNA_CLAUDE_DRIVER', default: "sdk", description: "Driver mode: \"sdk\" (API rates) or \"pty\" (subscription billing, macOS/Linux only)." },
  { name: 'KANNA_CLAUDE_SESSION_IDLE_MS', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_CLAUDE_SESSION_MAX_RESIDENT', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_CLAUDE_SESSION_SWEEP_INTERVAL_MS', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_DISABLE_SELF_UPDATE', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_LOG_ANALYTICS', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_LOG_CLAUDE_STEER', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_MCP_TOOL_CALLBACKS', default: "0", description: "Set to \"1\" to route AskUserQuestion / ExitPlanMode / built-in shims through the durable approval protocol." },
  { name: 'KANNA_PROFILE_SEND_TO_STARTING', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_PTY_E2E', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_RELOADER', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_REPO_DIR', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_RUNTIME_PROFILE', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_RUN_LIVE_TITLE_TESTS', default: "(undocumented)", description: "(no description — add one to extract-env-vars.ts DESCRIPTIONS)" },
  { name: 'KANNA_SERVER_SECRET', default: "(random per process)", description: "Stabilises HMAC tool-request ids across process restarts." },
]
