#!/usr/bin/env bun
// Scrapes src/**/*.ts for process.env.KANNA_* accesses, emits a TS data file.
// Hand-curated descriptions live in DESCRIPTIONS below.

import { Glob } from 'bun'
import path from 'node:path'

const REPO_ROOT = path.resolve(import.meta.dir, '../../')
const SRC = path.join(REPO_ROOT, 'src')
const OUT = path.join(import.meta.dir, '../src/content/docs/reference/env-vars-data.ts')

const DESCRIPTIONS: Record<string, { default: string; description: string }> = {
  KANNA_HOME: { default: '~/.kanna/', description: 'Data directory (chats, projects, OAuth pool, settings).' },
  KANNA_PORT: { default: '3210', description: 'HTTP server port.' },
  KANNA_PASSWORD: { default: '(unset)', description: 'HTTP/WS/API password gate. Recommended for exposed deployments.' },
  KANNA_CLAUDE_DRIVER: { default: 'sdk', description: 'Driver mode: "sdk" (API rates) or "pty" (subscription billing, macOS/Linux only).' },
  KANNA_MCP_TOOL_CALLBACKS: { default: '0', description: 'Set to "1" to route AskUserQuestion / ExitPlanMode / built-in shims through the durable approval protocol.' },
  KANNA_PTY_SANDBOX: { default: 'on', description: 'PTY OS-level sandbox. Set to "off" to disable (loses defense-in-depth).' },
  KANNA_PTY_PREFLIGHT_MODEL: { default: 'claude-haiku-4-5-20251001', description: 'Model used for allowlist preflight probes. Burns subscription turns — do not change unless cost is understood.' },
  KANNA_SERVER_SECRET: { default: '(random per process)', description: 'Stabilises HMAC tool-request ids across process restarts.' },
  KANNA_SYSTEM_PROMPT_APPEND: { default: '(unset)', description: 'Appended to the system prompt for every agent spawn (both SDK and PTY drivers).' },
}

const seen = new Set<string>()
const glob = new Glob('**/*.ts')

for await (const file of glob.scan({ cwd: SRC })) {
  const content = await Bun.file(path.join(SRC, file)).text()
  const matches = content.matchAll(/process\.env\.(KANNA_[A-Z0-9_]+)/g)
  for (const m of matches) seen.add(m[1])
}

const sorted = Array.from(seen).sort()
const lines = sorted.map(name => {
  const meta = DESCRIPTIONS[name] ?? { default: '(undocumented)', description: '(no description — add one to extract-env-vars.ts DESCRIPTIONS)' }
  return `  { name: '${name}', default: ${JSON.stringify(meta.default)}, description: ${JSON.stringify(meta.description)} },`
}).join('\n')

const out = `// Auto-generated by wiki/scripts/extract-env-vars.ts. Do not edit by hand.
export interface EnvVar { name: string; default: string; description: string }
export const envVars: EnvVar[] = [
${lines}
]
`

await Bun.write(OUT, out)
console.log(`Wrote ${sorted.length} env vars to ${OUT}`)
