#!/usr/bin/env bun
import { spawn } from "node:child_process"
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

const RATCHET_FILE = resolve(import.meta.dir, "..", ".lintratchet.json")
const RATCHETED_RULES = new Set(["no-restricted-imports", "no-restricted-globals"])
const args = process.argv.slice(2)
const updateMode = args.includes("--update")

interface EslintMessage {
  ruleId: string | null
  severity: 1 | 2
}

interface EslintFileResult {
  filePath: string
  messages: EslintMessage[]
}

interface RatchetSnapshot {
  total: number
  perRule: Record<string, number>
  updatedAt: string
  note: string
}

function runEslintJson(): Promise<EslintFileResult[]> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(
      "bunx",
      ["eslint", "--config", "eslint.ratchet.config.js", "--format", "json", "src/server"],
      { stdio: ["ignore", "pipe", "pipe"] },
    )
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString()
    })
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString()
    })
    child.on("close", (code) => {
      // ESLint exits 1 when warnings/errors are present; that is expected.
      if (code !== 0 && code !== 1) {
        reject(new Error(`eslint exited ${code}\n${stderr}`))
        return
      }
      try {
        resolvePromise(JSON.parse(stdout) as EslintFileResult[])
      } catch (err) {
        reject(new Error(`failed to parse eslint json: ${(err as Error).message}\n${stdout.slice(0, 400)}`))
      }
    })
  })
}

function countRatchetWarnings(results: EslintFileResult[]): { total: number; perRule: Record<string, number> } {
  const perRule: Record<string, number> = {}
  let total = 0
  for (const file of results) {
    for (const msg of file.messages) {
      if (msg.severity !== 1) continue
      if (!msg.ruleId || !RATCHETED_RULES.has(msg.ruleId)) continue
      perRule[msg.ruleId] = (perRule[msg.ruleId] ?? 0) + 1
      total += 1
    }
  }
  return { total, perRule }
}

function loadBaseline(): RatchetSnapshot | null {
  try {
    const raw = readFileSync(RATCHET_FILE, "utf8")
    return JSON.parse(raw) as RatchetSnapshot
  } catch {
    return null
  }
}

function writeBaseline(snapshot: RatchetSnapshot) {
  writeFileSync(RATCHET_FILE, JSON.stringify(snapshot, null, 2) + "\n", "utf8")
}

const eslintResults = await runEslintJson()
const counts = countRatchetWarnings(eslintResults)
const baseline = loadBaseline()

if (updateMode || !baseline) {
  const snapshot: RatchetSnapshot = {
    total: counts.total,
    perRule: counts.perRule,
    updatedAt: new Date().toISOString(),
    note: "Generated by scripts/lint-ratchet.ts --update. Lower-only ratchet: CI fails if total exceeds this value.",
  }
  writeBaseline(snapshot)
  console.log(`[ratchet] baseline written: total=${snapshot.total}`)
  console.log(JSON.stringify(snapshot, null, 2))
  process.exit(0)
}

console.log(`[ratchet] current=${counts.total} baseline=${baseline.total}`)
for (const [rule, count] of Object.entries(counts.perRule)) {
  console.log(`  ${rule}: ${count} (baseline ${baseline.perRule[rule] ?? 0})`)
}

if (counts.total > baseline.total) {
  console.error(
    `\n[ratchet] FAIL: ${counts.total - baseline.total} new side-effect site(s) in src/server.`,
  )
  console.error(
    `Fix by moving the call into src/server/**/*.adapter.ts (or src/server/adapters/**) or routing it through an injected port.`,
  )
  console.error(`Do NOT add an eslint-disable comment — that defeats the ratchet.`)
  process.exit(1)
}

if (counts.total < baseline.total) {
  console.log(
    `\n[ratchet] OK: ${baseline.total - counts.total} site(s) removed. Run \`bun run lint:ratchet -- --update\` and commit the new .lintratchet.json so the cap drops.`,
  )
} else {
  console.log(`\n[ratchet] OK: count unchanged.`)
}
process.exit(0)
